require: rubocop-performance

AllCops:
  TargetRubyVersion: 3.0

Layout/LineLength:
  Max: 99

Documentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
