require: rubocop-performance

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Layout/LineLength:
  Max: 99

Documentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false
