# GitHub actions workflow.
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

# https://scan.coverity.com/projects/ohloh_scm
name: Coverity Scan

on:
  push:
    branches: [main]

jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: vapier/coverity-scan-action@v1
      with:
        project: 'Ohloh_SCM'
        build_language: 'other'
        command: '--no-command --fs-capture-search ${{ github.workspace }}'
        email: ${{ secrets.COVERITY_SCAN_EMAIL }}
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
